apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-extension-job
  namespace: #@ self.namespace
spec:
  template:
    metadata:
      labels:
        purpose: "postgresql-extension" 
    spec:
      restartPolicy: "OnFailure"
      containers:
        #@ for database, user in self.databases.items():
        - name: #@ database + "-enable-extension"
          image: postgres:12
          command: #@ [ "psql", "-d", database, "-U", user, "-h",self.service, "-p", str(self.port) , "-c", "CREATE EXTENSION IF NOT EXISTS citext;"]
          env:
            - name: "PGPASSWORD"
              valueFrom:
                secretKeyRef:
                  name: #@ self.secret_name(database)
                  key: password
        #@ end