apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-extension-job
  namespace: #@ self.namespace
spec:
  template:
    metadata:
      labels:
        purpose: "postgresql-extension" 
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: enable-extension
          image: postgres:12
          command: #@ [ "psql", "-d", self.database, "-U", self.user, "-h",self.service, "-p", str(self.port) , "-c", "CREATE EXTENSION IF NOT EXISTS citext;"]
          env:
            - name: "PGPASSWORD"
              valueFrom:
                secretKeyRef:
                  name: #@ self.secretName
                  key: password
