apiVersion: v1
kind: Namespace
metadata:
  name: #@ self.namespace
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: #@ self.deploymentName
  namespace: #@ self.namespace
spec:
  teamId: #@ self.team
  volume:
    size: 1Gi
  numberOfInstances: 2
  #@ users = {}
  #@ databases = {}
  #@ for database, user in self.databases.items():
  #@   users[user] = ["superuser", "createdb"]
  #@   databases[database] = user
  #@ end
  users: #@ users
  databases: #@ databases
  postgresql:
    version: "12"
  #@ if self.cert != None:
  tls:
    secretName: #@ self.cert.name
    certificateFile: "tls.crt"
    privateKeyFile: "tls.key"
    caFile: "ca.crt"
  spiloFSGroup: 103
  #@ end
  