apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Release.Namespace }}
spec:
  teamId: "c21s"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    {{ .Values.user }}:  #! database owner
    - superuser
    - createdb
  databases:
    {{ .Values.database }}: {{ .Values.user }}  #! dbname: owner
  postgresql:
    version: "12"
